"use client";

import { motion } from "framer-motion";
import { CheckCircle, Zap, ArrowRight } from "lucide-react";
import Link from "next/link";
import { Button } from "@/components/ui/Button";

export default function AiAdGenerationPage() {
    return (
        <main className="min-h-screen pt-20 bg-[#050505] overflow-hidden">
            {/* Hero Section */}
            <section className="relative py-20 px-4">
                <div className="absolute top-0 left-1/2 -translate-x-1/2 w-full max-w-4xl h-96 bg-adquora-cyan/10 rounded-full blur-[128px] pointer-events-none" />

                <div className="max-w-7xl mx-auto text-center relative z-10">
                    <motion.div
                        initial={{ opacity: 0, y: 20 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ duration: 0.6 }}
                    >
                        <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full glass-panel mb-8 border-adquora-cyan/30">
                            <Zap size={16} className="text-adquora-cyan fill-current" />
                            <span className="text-sm font-medium text-cyan-100">AI-Powered Creativity</span>
                        </div>

                        <h1 className="text-5xl md:text-7xl font-bold font-display text-white mb-6">
                            High-Converting Ads <br />
                            <span className="text-gradient">Generated by AI.</span>
                        </h1>

                        <p className="text-xl text-gray-400 max-w-2xl mx-auto mb-12">
                            Stop wasting budget on A/B testing bad creatives. Our models are trained on
                            millions of winning ads to generate high-performing assets instantly.
                        </p>
                    </motion.div>
                </div>
            </section>

            {/* Pricing Section */}
            <section className="py-12 px-4">
                <div className="max-w-5xl mx-auto">
                    <div className="glass-card p-1 border-white/10 rounded-[2.5rem] relative overflow-hidden">
                        <div className="absolute inset-0 bg-gradient-to-b from-adquora-cyan/10 to-transparent pointer-events-none" />

                        <div className="bg-[#050505]/80 backdrop-blur-xl rounded-[2rem] p-8 md:p-16 flex flex-col md:flex-row items-center gap-12 relative z-10">

                            {/* Left: Value Prop */}
                            <div className="flex-1 space-y-8">
                                <h2 className="text-3xl font-bold text-white">Why Choose AI Ads?</h2>
                                <ul className="space-y-4">
                                    {[
                                        "Trained on $100M+ matching ad spend data",
                                        "24-48 Hour Turnaround Time",
                                        "Format-optimized for TikTok, Reels, & Shorts",
                                        "Includes Hooks, Body, and CTAs",
                                        "Click-Through Rate (CTR) Optimization"
                                    ].map((item, i) => (
                                        <li key={i} className="flex items-start gap-3 text-gray-300">
                                            <CheckCircle className="text-adquora-cyan shrink-0 mt-1" size={20} />
                                            <span>{item}</span>
                                        </li>
                                    ))}
                                </ul>
                            </div>

                            {/* Right: Pricing Card */}
                            <div className="w-full md:w-96">
                                <div className="glass-panel p-8 rounded-3xl border border-adquora-cyan/30 bg-adquora-cyan/5 text-center relative overflow-hidden group hover:border-adquora-cyan/50 transition-all duration-300">
                                    <div className="absolute -top-12 -right-12 w-32 h-32 bg-adquora-cyan/20 rounded-full blur-2xl group-hover:bg-adquora-cyan/30 transition-colors" />

                                    <h3 className="text-lg font-medium text-cyan-200 mb-2">Per Ad Creative</h3>
                                    <div className="flex items-baseline justify-center gap-1 mb-6">
                                        <span className="text-5xl font-bold text-white">$2,000</span>
                                        <span className="text-gray-400">/ ad</span>
                                    </div>

                                    <p className="text-gray-400 text-sm mb-8">
                                        Perfect for brands looking to scale aggressively with proven winner formats.
                                    </p>

                                    <Link href="/services/ai-ad-generation/create" className="block">
                                        <Button variant="primary" size="lg" width="full" className="w-full group" icon={<ArrowRight size={20} />} iconPosition="right">
                                            Get Started
                                        </Button>
                                    </Link>

                                    <p className="text-xs text-gray-500 mt-4">
                                        *Bulk discounts available for 5+ ads
                                    </p>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </section>
        </main>
    );
}
